### ISSUE TITLE
Entity unavailable - Sensor unknown

### ISSUE THREAD

**Issue by danielmbrown603** [rwoldberg/ldata-ha#14]
I am running LWHEM-2 with Gen2 breakers. 
I have the following errors in HA. 

![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/917e17fe-9221-4fce-bcfd-29d5b0af0398)

Thank you, awesome project!

**Comment by rwoldberg** [comment]
Very strange, give it a little but and see if it clears up.

**Comment by danielmbrown603** [comment]
Sounds good, will do

**Comment by rwoldberg** [comment]
I am going to look at my code and see if there is anything that I could be doing wrong.  I don't have a LWHEM-2 or any Gen-2 breakers, so its a bit difficult to diagnose any issues with them.

**Comment by rwoldberg** [comment]
I added some checks that might help with this issue.

**Comment by danielmbrown603** [comment]
![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/7077c145-ae20-4e35-9dc6-9c15674c8b7a)
Looks good, thanks for the fix!

**Comment by rwoldberg** [comment]
Great.

**Comment by danielmbrown603** [comment]
Looks like I spoke too soon. That error is back. I also noticed that the breakers don’t show total daily energy, shows up as unknown.
![IMG_0666](https://github.com/rwoldberg/ldata-ha/assets/79930376/125c8b6d-0873-44c1-a03d-50b572ed82f1)
![IMG_0665](https://github.com/rwoldberg/ldata-ha/assets/79930376/e7af4568-6a83-4125-9daf-5abfa8771d27)

**Comment by rwoldberg** [comment]
Are these Gen2 devices?

**Comment by danielmbrown603** [comment]
> Are these Gen2 devices?

Yes, they are.

**Comment by rwoldberg** [comment]
Would you be willing to send me some data to maybe help with figuring this out?

**Comment by danielmbrown603** [comment]
> Would you be willing to send me some data to maybe help with figuring this out?

Yes, more than happy to help.

**Comment by rwoldberg** [comment]
Great.   What I need is for you to open my.leviton.com login and open the developer tools, found in the '...' under 'More tools'. Then go to the panel view for the module.  Refresh the page, then select all from the network tab in the developer tools.  You should then be able to right click on of the items that is selected and click 'Save all as HAR with content'.  When you have this, send it to me via email, you can find my email in my profile.

**Comment by djcutch** [comment]
If you need any logs from me as well they just fix and patch an issues i reported with Gen1 breakers and lwhem2 i plan on getting gen2 breakers in a couple weeks trying to buy out local hd of gen1.

**Comment by rwoldberg** [comment]
I made some small changes, update the integration and let me know if it helps.

**Comment by MHillyer** [comment]
I'm getting the same on the 1.0.16 release, but I do not have Gen2 breakers.

**Comment by djcutch** [comment]
yep mine is totaly broken with lwhem and gen 1 breaker.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ldata/binary_sensor.py", line 24, in async_setup_entry
    for breaker_id in entry.data["breakers"]:
                      ~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-17 10:09:15.260 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ldata platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ldata/sensor.py", line 90, in async_setup_entry
    for breaker_id in entry.data["breakers"]:
                      ~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-17 10:09:15.262 ERROR (MainThread) [homeassistant.components.switch] Error while setting up ldata platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ldata/switch.py", line 32, in async_setup_entry
    for breaker_id in entry.data["breakers"]:
                      ~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-17 10:09:52.148 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139757035019584] James McCutcheon from 192.168.3.69 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0): Client unable to keep up with pending messages. Stayed over 1024 for 5 seconds. The system's load is too high or an integration is misbehaving; Last message was: {"id":91,"type":"event","event":{"stage":"running"}}

**Comment by rwoldberg** [comment]
@djcutch That part of the code has not change.  That almost looks like it failed to get the data from leviton.

**Comment by rwoldberg** [comment]
I noticed there was an exception that was being caught but not logged.  I created a new version that logs this now. Maybe this will help track down the issue.  It should be available to install now if you update the information for the integration.

**Comment by free9d9** [comment]
Im using an LDATA and gen 1 breakers. All my entities are unavailable. I just did the update to 1.0.17. Let me know what data you need and I can help at all. Cheers!

**Comment by rwoldberg** [comment]
Turn on debug logs for the integration and look for any errors from LDATA in the logs.  I am hoping to see something there will show what is happening.   I have been using this integration for almost a year and have never seen this error on my system.

**Comment by free9d9** [comment]
Ya same. 6 months or so without issue. I recently did a bunch of updates and that was when this integration broke :\

**Comment by rwoldberg** [comment]
@free9d9  I think that is a login issue.

**Comment by free9d9** [comment]
Thats what I was thinking as well, so earlier I tried to delete the entry and set it up again. Then I got failure to authenticate with leviton API. But my login info hasnt changed.

**Comment by rwoldberg** [comment]
Can you still login to my.leviton.com?

**Comment by infotechjrf** [comment]
Same here, had to Password Reset my account too.

**Comment by free9d9** [comment]
Anyone else having issues with the daily consumption? I do seem to be getting an error as well.

Logger: ldata
Source: custom_components/ldata/sensor.py:258
Integration: Leviton LDATA (documentation, issues)
First occurred: 8:34:36 AM (16120 occurrences)
Last logged: 4:52:14 PM

Error updating sensor! unsupported operand type(s) for +: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/config/custom_components/ldata/sensor.py", line 258, in _state_update
    self._state = self._state + (power * time_span)
                  ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

**Comment by danielmbrown603** [comment]
![IMG_0745](https://github.com/rwoldberg/ldata-ha/assets/79930376/ca4dba69-7de1-47f7-8b0e-58cd64b2544a)
![IMG_0743](https://github.com/rwoldberg/ldata-ha/assets/79930376/00eaa186-b385-410f-9856-61d29f92edf3)
![IMG_0742](https://github.com/rwoldberg/ldata-ha/assets/79930376/796bb5be-8e33-465e-a85f-a9236481f542)


I get these UNKNOWN errors

**Comment by rwoldberg** [comment]
@free9d9  Thanks, that is helpful, I will try and track that down tomorrow morning.

**Comment by free9d9** [comment]
I also noticed that if I reload the integration all my values go back to 0kWh used for the day (except the whole home which shows proper amount) and they all seem to work for a while then go to unknown some time later. I'll try to gather for info over the next 24 hours. I just reconfigured it to read-only mode. I'll see if that makes a difference.

**Comment by rwoldberg** [comment]
Read only mode just removes the switches, so that should have no effect.  I will push some new code tomorrow morning.

**Comment by free9d9** [comment]
Ahh, gotcha. makes sense. Well I came to hopefully provide some useful data. But everything is working perfect since the HA restart yesterday. All daily values are accounted for.

**Comment by rwoldberg** [comment]
I pushed a new release that should hopefully keep this from happening.

**Comment by rwoldberg** [comment]
If the latest update fixes the issue for anyone, please let me know.  Thanks.

**Comment by free9d9** [comment]
Everything seems to be working great! Thanks again.

**Comment by danielmbrown603** [comment]
Seems to be working, but the error was random. I’ll keep checking for another day or two and let you know.

**Comment by prabhu-madanagopal** [comment]
Hi 
Same issue, still having issues with v1.0.18. 
Had to reset password due to multiple attempts few days back, then everything works except total daily energy.
It is on and off, sometimes unavailable, sometimes works, now it is 0.
Pls let me know if you need any more information.

**Comment by prabhu-madanagopal** [comment]
After restart it works, the same happened last time, when restart fixes it. will let you know if it recurs.

**Comment by danielmbrown603** [comment]
Still working well, haven't seen any errors in the gui. with 1.0.19

I am about to install 1.0.20

**Comment by rwoldberg** [comment]
@danielmbrown603 I introduced a stupid bug in 1.0.19, it was not updating the daily energy for any device, 1.0.20 fixes that.

**Comment by danielmbrown603** [comment]
After the upgrade, I had an unexpected spike in the energy graph, compared to the previous hours. Not sure what happened but that 1-hour spike is usually 2/3's of my total daily usage in a winter day. Change in calculations?

![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/003912a4-7c73-4a49-96a7-ebb5581a06b5)
![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/3cc26ed9-2116-418b-aa3d-c00aa3f2b0c4)


If I look at whats driving most of my usage (heat pump), there was no monumental spike like that. 
![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/d34d61b0-f7e3-4e9d-ad96-455990cef598)
![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/f47fd748-f05b-45e5-9237-54426b673392)

**Comment by rwoldberg** [comment]
No, the calculations have not changed.  I think it was probably because of the bug, no data was being updated for the daily energy sensors, then with the patch applied they stated reporting again.  That should be a one time issue.

**Comment by rwoldberg** [comment]
I am going to mark this as fixed unless someone says they are still having issues.
